# Generated by Django 5.2.11 on 2026-02-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the host', max_length=100)),
                ('hostname', models.CharField(help_text='IP address or domain', max_length=255)),
                ('username', models.CharField(help_text='SSH username', max_length=100)),
                ('password', models.CharField(help_text='SSH password (plaintext for MVP)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text="User's natural language instruction")),
                ('generated_command', models.TextField(blank=True, help_text='Gemini-generated bash command')),
                ('output', models.TextField(blank=True, help_text='Command execution output')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agent.remotehost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
