# Generated by Django 6.0.1 on 2026-02-17 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_chatsession_alter_agenttask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='generated_command',
            field=models.TextField(blank=True, help_text='Primary command or summary'),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='output',
            field=models.TextField(blank=True, help_text='Final analysis or output'),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('thought', models.TextField(blank=True, help_text='AI reasoning before action')),
                ('command', models.TextField(blank=True, help_text='Command executed')),
                ('output', models.TextField(blank=True, help_text='Raw command output')),
                ('analysis', models.TextField(blank=True, help_text='AI analysis of the output')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent.agenttask')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
