# Generated by Django 5.2.11 on 2026-02-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_agenttask_generated_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotehost',
            name='use_sudo',
            field=models.BooleanField(default=False, help_text='User has sudo privileges (password used for sudo)'),
        ),
    ]
